server:
  port: 8127
spring:
  profiles:
    active: debug,dev
  application:
    name: coinbase
  datasource:
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:${app.home:${user.home}}/h2/coinbase;SCHEMA=COINBASE;
    username: coinbase
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
logging:
  file:
    path: ${app.home:${user.home}}/logs
okhttp:
  connect-timeout-ms: 5000
  keep-alive-duration-sec: 1000
  max-idle: 1000
  read-timeout-ms: 5000
  write-timeout-ms: 5000
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/swagger-ui.html